version: "3.6"
services:
  registry:
    image: registry:2
    ports: 
      - 5000:5000
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.cicd == true
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/domain.crt"
      REGISTRY_HTTP_TLS_KEY: "/certs/domain.key"
    volumes:
      - /etc/letsencrypt/live/reg.aichallenge.ir:/certs
      - regdata:/var/lib/registry 

  gitlab:
    image: gitlab/gitlab-ee:13.5.4-ee.0
    hostname: giti.aichallenge.ir
    ports:
      - "22:22"
      - "30080:80"
      - "30443:443"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.cicd == true
    volumes:
      - /srv/gitlab/data:/var/opt/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/config:/etc/gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    volumes:
      - gitlab-runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.cicd == true
volumes:
  regdata:
  gitlab-runner-config:
