version: "3.8"
services: 
  minio:
    image: minio/minio
    container_name: minio
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.minio == true]
    volumes: 
      - /var/lib/minio:/data
    networks: 
      - host
    ports:
      - 9001:9000
    secrets:
      - minio_access_key
      - minio_secret_key
    environment: 
      MINIO_ACCESS_KEY_FILE: /run/secrets/minio_access_key
      MINIO_SECRET_KEY_FILE: /run/secrets/minio_secret_key
    command: ["server", "/data"]

networks: 
  host:

secrets:
  minio_access_key:
    external: true
  minio_secret_key:
    external: true
