# infra test enviorment
version: '3.6'

services:
  saint-peters-gates:
    image: saint-peters-gates
    networks:
      - network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.cicd == true
    environment:
      KAFKA_ENDPOINT: "kn1.aichallenge.ir:9092,kn2.aichallenge.ir:9092,kn3.aichallenge.ir:9092"
      KAFKA_TOPIC_STORE_CODE: "store-code"
      KAFKA_TOPIC_MATCH_0_PARTITIONS: 10
      KAFKA_TOPIC_MATCH_1_PARTITIONS: 10
      KAFKA_TOPIC_MATCH_0: "jj"
      KAFKA_TOPIC_MATCH_1: "jj"
      MINIO_ENDPOINT: "minio.aichallenge.ir:9001"
      MINIO_ACCESS_KEY: "ngnFxoPBtPZjBS7m4x12Yb1q5FovKGa4Bl9PsENs13nmDTRp"
      MINIO_SECRET_KEY: "RuRRYyZKbOwVnkyNRYq1f7CRPq89XqOwFHkxoTY4Epq0fvHh"
      MINIO_BUCKET_CODE: "code"
      MINIO_BUCKET_MAP: "map"
      MINIO_BUCKET_LOG: "log"
      MINIO_DOWNLOAD_LINK_DOMAIN: "https://storage.aichallenge.ir"
      BACKEND_TOKEN: "y:ezHR8w/hw&WRz3n}]wh!!)3Q;s:NC=JwE;BWa~"

    command: >
      sh -c "
        ./manage.py compilemessages;
        gunicorn --bind=0.0.0.0:8000 --timeout=90  --workers=1 --threads=10 --preload gateway.wsgi:application;
      "
    ports:
      - 6008:8000

  final_judgment:
    image: reg.aichallenge.ir/aic/infra/final_judgment:521-fca8d683
    networks:
      - network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.cicd == true
    environment:
      KAFKA_ENDPOINT: "kn1.aichallenge.ir:9092,kn2.aichallenge.ir:9092,kn3.aichallenge.ir:9092"
      KAFKA_TOPIC_MATCH: "jj"
      KAFKA_TOPIC_EVENTS: "events-test"
      KAFKA_TOPIC_CONSUMER_GROUP: "rr-test"
      KAFKA_CONSUMER_HEART_BEAT_TIMEOUT: "120000"
      MINIO_ENDPOINT: "minio.aichallenge.ir:9001"
      MINIO_ACCESS_KEY: "ngnFxoPBtPZjBS7m4x12Yb1q5FovKGa4Bl9PsENs13nmDTRp"
      MINIO_SECRET_KEY: "RuRRYyZKbOwVnkyNRYq1f7CRPq89XqOwFHkxoTY4Epq0fvHh"
      MINIO_BUCKET_CODE: "code"
      MINIO_BUCKET_MAP: "map"
      MINIO_BUCKET_LOG: "log"

      MATCH_TIMEOUT: "600"
      
    command: "python3 -u main.py"

networks:
  network:

